SEED: 0

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: ""
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [ [ 32 ], [ 64 ], [ 128 ], [ 256 ], [ 512 ] ]
    ASPECT_RATIOS: [ [ 0.5, 1.0, 2.0 ] ]
  RPN:
    IN_FEATURES: [ "p2", "p3", "p4", "p5", "p6" ]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 80
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
    FC_DIM: 1024
    CONV_DIM: 256
    CLS_AGNOSTIC_BBOX_REG: False
    TRAIN_ON_PRED_BOXES: False
  ROI_MASK_HEAD:
    NORM: "SyncBN"
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 0
  MASK_ON: True

  PIXEL_MEAN:  [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 0
  PRECISE_BN:
    ENABLED: True

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  AMP:
    ENABLED: True

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

VIS_PERIOD: 0